// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: households.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHouseholdsByStreetID = `-- name: CountHouseholdsByStreetID :one
SELECT count(*) FROM households
WHERE street_id = $1
`

func (q *Queries) CountHouseholdsByStreetID(ctx context.Context, streetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countHouseholdsByStreetID, streetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (
    mfy_id,
    street_id,
    house_number,
    total_numbers,
    contacted_numbers,
    voted_numbers,
    status,
    notes,
    assigned_responsible_user_id,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, mfy_id, street_id, house_number, total_numbers, contacted_numbers, voted_numbers, status, notes, assigned_responsible_user_id, created_by_user_id, created_at, updated_at
`

type CreateHouseholdParams struct {
	MfyID                     pgtype.UUID
	StreetID                  pgtype.UUID
	HouseNumber               string
	TotalNumbers              int32
	ContactedNumbers          int32
	VotedNumbers              int32
	Status                    string
	Notes                     pgtype.Text
	AssignedResponsibleUserID pgtype.UUID
	CreatedByUserID           pgtype.UUID
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold,
		arg.MfyID,
		arg.StreetID,
		arg.HouseNumber,
		arg.TotalNumbers,
		arg.ContactedNumbers,
		arg.VotedNumbers,
		arg.Status,
		arg.Notes,
		arg.AssignedResponsibleUserID,
		arg.CreatedByUserID,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.MfyID,
		&i.StreetID,
		&i.HouseNumber,
		&i.TotalNumbers,
		&i.ContactedNumbers,
		&i.VotedNumbers,
		&i.Status,
		&i.Notes,
		&i.AssignedResponsibleUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHousehold = `-- name: DeleteHousehold :exec
DELETE FROM households
WHERE id = $1
`

func (q *Queries) DeleteHousehold(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHousehold, id)
	return err
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, mfy_id, street_id, house_number, total_numbers, contacted_numbers, voted_numbers, status, notes, assigned_responsible_user_id, created_by_user_id, created_at, updated_at FROM households
WHERE id = $1
`

func (q *Queries) GetHouseholdByID(ctx context.Context, id pgtype.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.MfyID,
		&i.StreetID,
		&i.HouseNumber,
		&i.TotalNumbers,
		&i.ContactedNumbers,
		&i.VotedNumbers,
		&i.Status,
		&i.Notes,
		&i.AssignedResponsibleUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHouseholdsByMFYID = `-- name: ListHouseholdsByMFYID :many
SELECT id, mfy_id, street_id, house_number, total_numbers, contacted_numbers, voted_numbers, status, notes, assigned_responsible_user_id, created_by_user_id, created_at, updated_at FROM households
WHERE mfy_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListHouseholdsByMFYIDParams struct {
	MfyID  pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListHouseholdsByMFYID(ctx context.Context, arg ListHouseholdsByMFYIDParams) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholdsByMFYID, arg.MfyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.MfyID,
			&i.StreetID,
			&i.HouseNumber,
			&i.TotalNumbers,
			&i.ContactedNumbers,
			&i.VotedNumbers,
			&i.Status,
			&i.Notes,
			&i.AssignedResponsibleUserID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsByResponsibleUserID = `-- name: ListHouseholdsByResponsibleUserID :many
SELECT id, mfy_id, street_id, house_number, total_numbers, contacted_numbers, voted_numbers, status, notes, assigned_responsible_user_id, created_by_user_id, created_at, updated_at FROM households
WHERE assigned_responsible_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListHouseholdsByResponsibleUserIDParams struct {
	AssignedResponsibleUserID pgtype.UUID
	Limit                     int32
	Offset                    int32
}

func (q *Queries) ListHouseholdsByResponsibleUserID(ctx context.Context, arg ListHouseholdsByResponsibleUserIDParams) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholdsByResponsibleUserID, arg.AssignedResponsibleUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.MfyID,
			&i.StreetID,
			&i.HouseNumber,
			&i.TotalNumbers,
			&i.ContactedNumbers,
			&i.VotedNumbers,
			&i.Status,
			&i.Notes,
			&i.AssignedResponsibleUserID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsByStreetID = `-- name: ListHouseholdsByStreetID :many
SELECT id, mfy_id, street_id, house_number, total_numbers, contacted_numbers, voted_numbers, status, notes, assigned_responsible_user_id, created_by_user_id, created_at, updated_at FROM households
WHERE street_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListHouseholdsByStreetIDParams struct {
	StreetID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListHouseholdsByStreetID(ctx context.Context, arg ListHouseholdsByStreetIDParams) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholdsByStreetID, arg.StreetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.MfyID,
			&i.StreetID,
			&i.HouseNumber,
			&i.TotalNumbers,
			&i.ContactedNumbers,
			&i.VotedNumbers,
			&i.Status,
			&i.Notes,
			&i.AssignedResponsibleUserID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseholdsByStreetIDs = `-- name: ListHouseholdsByStreetIDs :many
SELECT id, mfy_id, street_id, house_number, total_numbers, contacted_numbers, voted_numbers, status, notes, assigned_responsible_user_id, created_by_user_id, created_at, updated_at FROM households
WHERE street_id = ANY($1::uuid[])
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListHouseholdsByStreetIDsParams struct {
	Column1 []pgtype.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListHouseholdsByStreetIDs(ctx context.Context, arg ListHouseholdsByStreetIDsParams) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholdsByStreetIDs, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.MfyID,
			&i.StreetID,
			&i.HouseNumber,
			&i.TotalNumbers,
			&i.ContactedNumbers,
			&i.VotedNumbers,
			&i.Status,
			&i.Notes,
			&i.AssignedResponsibleUserID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHouseholdStatus = `-- name: SetHouseholdStatus :one
UPDATE households
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, mfy_id, street_id, house_number, total_numbers, contacted_numbers, voted_numbers, status, notes, assigned_responsible_user_id, created_by_user_id, created_at, updated_at
`

type SetHouseholdStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) SetHouseholdStatus(ctx context.Context, arg SetHouseholdStatusParams) (Household, error) {
	row := q.db.QueryRow(ctx, setHouseholdStatus, arg.ID, arg.Status)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.MfyID,
		&i.StreetID,
		&i.HouseNumber,
		&i.TotalNumbers,
		&i.ContactedNumbers,
		&i.VotedNumbers,
		&i.Status,
		&i.Notes,
		&i.AssignedResponsibleUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE households
SET
    house_number = $2,
    total_numbers = $3,
    contacted_numbers = $4,
    voted_numbers = $5,
    status = $6,
    notes = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, mfy_id, street_id, house_number, total_numbers, contacted_numbers, voted_numbers, status, notes, assigned_responsible_user_id, created_by_user_id, created_at, updated_at
`

type UpdateHouseholdParams struct {
	ID               pgtype.UUID
	HouseNumber      string
	TotalNumbers     int32
	ContactedNumbers int32
	VotedNumbers     int32
	Status           string
	Notes            pgtype.Text
}

func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, updateHousehold,
		arg.ID,
		arg.HouseNumber,
		arg.TotalNumbers,
		arg.ContactedNumbers,
		arg.VotedNumbers,
		arg.Status,
		arg.Notes,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.MfyID,
		&i.StreetID,
		&i.HouseNumber,
		&i.TotalNumbers,
		&i.ContactedNumbers,
		&i.VotedNumbers,
		&i.Status,
		&i.Notes,
		&i.AssignedResponsibleUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHouseholdAssignment = `-- name: UpdateHouseholdAssignment :one
UPDATE households
SET assigned_responsible_user_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, mfy_id, street_id, house_number, total_numbers, contacted_numbers, voted_numbers, status, notes, assigned_responsible_user_id, created_by_user_id, created_at, updated_at
`

type UpdateHouseholdAssignmentParams struct {
	ID                        pgtype.UUID
	AssignedResponsibleUserID pgtype.UUID
}

func (q *Queries) UpdateHouseholdAssignment(ctx context.Context, arg UpdateHouseholdAssignmentParams) (Household, error) {
	row := q.db.QueryRow(ctx, updateHouseholdAssignment, arg.ID, arg.AssignedResponsibleUserID)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.MfyID,
		&i.StreetID,
		&i.HouseNumber,
		&i.TotalNumbers,
		&i.ContactedNumbers,
		&i.VotedNumbers,
		&i.Status,
		&i.Notes,
		&i.AssignedResponsibleUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
