// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: household_change_logs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHouseholdChangeLog = `-- name: CreateHouseholdChangeLog :one
INSERT INTO household_change_logs (
    household_id,
    changed_by_user_id,
    field_name,
    old_value,
    new_value,
    note
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, household_id, changed_by_user_id, field_name, old_value, new_value, note, created_at
`

type CreateHouseholdChangeLogParams struct {
	HouseholdID     pgtype.UUID
	ChangedByUserID pgtype.UUID
	FieldName       string
	OldValue        pgtype.Text
	NewValue        pgtype.Text
	Note            pgtype.Text
}

func (q *Queries) CreateHouseholdChangeLog(ctx context.Context, arg CreateHouseholdChangeLogParams) (HouseholdChangeLog, error) {
	row := q.db.QueryRow(ctx, createHouseholdChangeLog,
		arg.HouseholdID,
		arg.ChangedByUserID,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.Note,
	)
	var i HouseholdChangeLog
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.ChangedByUserID,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listHouseholdChangeLogsByHouseholdID = `-- name: ListHouseholdChangeLogsByHouseholdID :many
SELECT id, household_id, changed_by_user_id, field_name, old_value, new_value, note, created_at FROM household_change_logs
WHERE household_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListHouseholdChangeLogsByHouseholdIDParams struct {
	HouseholdID pgtype.UUID
	Limit       int32
	Offset      int32
}

func (q *Queries) ListHouseholdChangeLogsByHouseholdID(ctx context.Context, arg ListHouseholdChangeLogsByHouseholdIDParams) ([]HouseholdChangeLog, error) {
	rows, err := q.db.Query(ctx, listHouseholdChangeLogsByHouseholdID, arg.HouseholdID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HouseholdChangeLog
	for rows.Next() {
		var i HouseholdChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.ChangedByUserID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
