// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfys.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserToMFY = `-- name: AssignUserToMFY :one
UPDATE users
SET mfy_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at
`

type AssignUserToMFYParams struct {
	ID    pgtype.UUID
	MfyID pgtype.UUID
}

func (q *Queries) AssignUserToMFY(ctx context.Context, arg AssignUserToMFYParams) (User, error) {
	row := q.db.QueryRow(ctx, assignUserToMFY, arg.ID, arg.MfyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.Role,
		&i.MfyID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMFY = `-- name: CreateMFY :one
INSERT INTO mfys (
    name,
    region,
    district,
    target_votes,
    season,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, region, district, target_votes, season, is_active, created_by_user_id, created_at, updated_at
`

type CreateMFYParams struct {
	Name            string
	Region          pgtype.Text
	District        pgtype.Text
	TargetVotes     pgtype.Int4
	Season          pgtype.Text
	CreatedByUserID pgtype.UUID
}

func (q *Queries) CreateMFY(ctx context.Context, arg CreateMFYParams) (Mfy, error) {
	row := q.db.QueryRow(ctx, createMFY,
		arg.Name,
		arg.Region,
		arg.District,
		arg.TargetVotes,
		arg.Season,
		arg.CreatedByUserID,
	)
	var i Mfy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.District,
		&i.TargetVotes,
		&i.Season,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMFYByID = `-- name: GetMFYByID :one
SELECT id, name, region, district, target_votes, season, is_active, created_by_user_id, created_at, updated_at FROM mfys
WHERE id = $1
`

func (q *Queries) GetMFYByID(ctx context.Context, id pgtype.UUID) (Mfy, error) {
	row := q.db.QueryRow(ctx, getMFYByID, id)
	var i Mfy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.District,
		&i.TargetVotes,
		&i.Season,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByMFYID = `-- name: GetUsersByMFYID :many
SELECT id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at FROM users
WHERE mfy_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUsersByMFYID(ctx context.Context, mfyID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByMFYID, mfyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.TelegramID,
			&i.TelegramUsername,
			&i.Role,
			&i.MfyID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMFYs = `-- name: ListMFYs :many
SELECT id, name, region, district, target_votes, season, is_active, created_by_user_id, created_at, updated_at FROM mfys
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMFYsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListMFYs(ctx context.Context, arg ListMFYsParams) ([]Mfy, error) {
	rows, err := q.db.Query(ctx, listMFYs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mfy
	for rows.Next() {
		var i Mfy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.District,
			&i.TargetVotes,
			&i.Season,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMFYActive = `-- name: SetMFYActive :one
UPDATE mfys
SET is_active = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, region, district, target_votes, season, is_active, created_by_user_id, created_at, updated_at
`

type SetMFYActiveParams struct {
	ID       pgtype.UUID
	IsActive bool
}

func (q *Queries) SetMFYActive(ctx context.Context, arg SetMFYActiveParams) (Mfy, error) {
	row := q.db.QueryRow(ctx, setMFYActive, arg.ID, arg.IsActive)
	var i Mfy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.District,
		&i.TargetVotes,
		&i.Season,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMFY = `-- name: UpdateMFY :one
UPDATE mfys
SET
    name = $2,
    region = $3,
    district = $4,
    target_votes = $5,
    season = $6,
    is_active = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, name, region, district, target_votes, season, is_active, created_by_user_id, created_at, updated_at
`

type UpdateMFYParams struct {
	ID          pgtype.UUID
	Name        string
	Region      pgtype.Text
	District    pgtype.Text
	TargetVotes pgtype.Int4
	Season      pgtype.Text
	IsActive    bool
}

func (q *Queries) UpdateMFY(ctx context.Context, arg UpdateMFYParams) (Mfy, error) {
	row := q.db.QueryRow(ctx, updateMFY,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.District,
		arg.TargetVotes,
		arg.Season,
		arg.IsActive,
	)
	var i Mfy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.District,
		&i.TargetVotes,
		&i.Season,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
