// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID               pgtype.UUID
	FullName         string
	Phone            pgtype.Text
	TelegramID       pgtype.Int8
	TelegramUsername pgtype.Text
	Role             string
	MfyID            pgtype.UUID
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
