// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: responsible_assignments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResponsibleAssignment = `-- name: CreateResponsibleAssignment :one
INSERT INTO responsible_assignments (
    street_id,
    responsible_user_id,
    assigned_by_user_id,
    from_house_number,
    to_house_number
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, street_id, responsible_user_id, assigned_by_user_id, from_house_number, to_house_number, is_active, created_at, updated_at
`

type CreateResponsibleAssignmentParams struct {
	StreetID          pgtype.UUID
	ResponsibleUserID pgtype.UUID
	AssignedByUserID  pgtype.UUID
	FromHouseNumber   string
	ToHouseNumber     string
}

func (q *Queries) CreateResponsibleAssignment(ctx context.Context, arg CreateResponsibleAssignmentParams) (ResponsibleAssignment, error) {
	row := q.db.QueryRow(ctx, createResponsibleAssignment,
		arg.StreetID,
		arg.ResponsibleUserID,
		arg.AssignedByUserID,
		arg.FromHouseNumber,
		arg.ToHouseNumber,
	)
	var i ResponsibleAssignment
	err := row.Scan(
		&i.ID,
		&i.StreetID,
		&i.ResponsibleUserID,
		&i.AssignedByUserID,
		&i.FromHouseNumber,
		&i.ToHouseNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateResponsibleAssignment = `-- name: DeactivateResponsibleAssignment :one
UPDATE responsible_assignments
SET is_active = false, updated_at = now()
WHERE id = $1
RETURNING id, street_id, responsible_user_id, assigned_by_user_id, from_house_number, to_house_number, is_active, created_at, updated_at
`

func (q *Queries) DeactivateResponsibleAssignment(ctx context.Context, id pgtype.UUID) (ResponsibleAssignment, error) {
	row := q.db.QueryRow(ctx, deactivateResponsibleAssignment, id)
	var i ResponsibleAssignment
	err := row.Scan(
		&i.ID,
		&i.StreetID,
		&i.ResponsibleUserID,
		&i.AssignedByUserID,
		&i.FromHouseNumber,
		&i.ToHouseNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResponsibleAssignmentByID = `-- name: GetResponsibleAssignmentByID :one
SELECT id, street_id, responsible_user_id, assigned_by_user_id, from_house_number, to_house_number, is_active, created_at, updated_at FROM responsible_assignments
WHERE id = $1
`

func (q *Queries) GetResponsibleAssignmentByID(ctx context.Context, id pgtype.UUID) (ResponsibleAssignment, error) {
	row := q.db.QueryRow(ctx, getResponsibleAssignmentByID, id)
	var i ResponsibleAssignment
	err := row.Scan(
		&i.ID,
		&i.StreetID,
		&i.ResponsibleUserID,
		&i.AssignedByUserID,
		&i.FromHouseNumber,
		&i.ToHouseNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isResponsibleAssignedToStreet = `-- name: IsResponsibleAssignedToStreet :one
SELECT EXISTS (
    SELECT 1 FROM responsible_assignments
    WHERE street_id = $1 AND responsible_user_id = $2 AND is_active = true
)
`

type IsResponsibleAssignedToStreetParams struct {
	StreetID          pgtype.UUID
	ResponsibleUserID pgtype.UUID
}

func (q *Queries) IsResponsibleAssignedToStreet(ctx context.Context, arg IsResponsibleAssignedToStreetParams) (bool, error) {
	row := q.db.QueryRow(ctx, isResponsibleAssignedToStreet, arg.StreetID, arg.ResponsibleUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveResponsibleAssignmentsByStreetID = `-- name: ListActiveResponsibleAssignmentsByStreetID :many
SELECT id, street_id, responsible_user_id, assigned_by_user_id, from_house_number, to_house_number, is_active, created_at, updated_at FROM responsible_assignments
WHERE street_id = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveResponsibleAssignmentsByStreetIDParams struct {
	StreetID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListActiveResponsibleAssignmentsByStreetID(ctx context.Context, arg ListActiveResponsibleAssignmentsByStreetIDParams) ([]ResponsibleAssignment, error) {
	rows, err := q.db.Query(ctx, listActiveResponsibleAssignmentsByStreetID, arg.StreetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResponsibleAssignment
	for rows.Next() {
		var i ResponsibleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.StreetID,
			&i.ResponsibleUserID,
			&i.AssignedByUserID,
			&i.FromHouseNumber,
			&i.ToHouseNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponsibleAssignmentsByResponsibleUserID = `-- name: ListResponsibleAssignmentsByResponsibleUserID :many
SELECT id, street_id, responsible_user_id, assigned_by_user_id, from_house_number, to_house_number, is_active, created_at, updated_at FROM responsible_assignments
WHERE responsible_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResponsibleAssignmentsByResponsibleUserIDParams struct {
	ResponsibleUserID pgtype.UUID
	Limit             int32
	Offset            int32
}

func (q *Queries) ListResponsibleAssignmentsByResponsibleUserID(ctx context.Context, arg ListResponsibleAssignmentsByResponsibleUserIDParams) ([]ResponsibleAssignment, error) {
	rows, err := q.db.Query(ctx, listResponsibleAssignmentsByResponsibleUserID, arg.ResponsibleUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResponsibleAssignment
	for rows.Next() {
		var i ResponsibleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.StreetID,
			&i.ResponsibleUserID,
			&i.AssignedByUserID,
			&i.FromHouseNumber,
			&i.ToHouseNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponsibleAssignmentsByStreetID = `-- name: ListResponsibleAssignmentsByStreetID :many
SELECT id, street_id, responsible_user_id, assigned_by_user_id, from_house_number, to_house_number, is_active, created_at, updated_at FROM responsible_assignments
WHERE street_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListResponsibleAssignmentsByStreetIDParams struct {
	StreetID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListResponsibleAssignmentsByStreetID(ctx context.Context, arg ListResponsibleAssignmentsByStreetIDParams) ([]ResponsibleAssignment, error) {
	rows, err := q.db.Query(ctx, listResponsibleAssignmentsByStreetID, arg.StreetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResponsibleAssignment
	for rows.Next() {
		var i ResponsibleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.StreetID,
			&i.ResponsibleUserID,
			&i.AssignedByUserID,
			&i.FromHouseNumber,
			&i.ToHouseNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
