// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: street_leader_assignments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStreetLeaderAssignment = `-- name: CreateStreetLeaderAssignment :one
INSERT INTO street_leader_assignments (
    street_id,
    user_id,
    assigned_by_user_id
) VALUES (
    $1, $2, $3
)
RETURNING id, street_id, user_id, assigned_by_user_id, is_active, created_at, updated_at
`

type CreateStreetLeaderAssignmentParams struct {
	StreetID         pgtype.UUID
	UserID           pgtype.UUID
	AssignedByUserID pgtype.UUID
}

func (q *Queries) CreateStreetLeaderAssignment(ctx context.Context, arg CreateStreetLeaderAssignmentParams) (StreetLeaderAssignment, error) {
	row := q.db.QueryRow(ctx, createStreetLeaderAssignment, arg.StreetID, arg.UserID, arg.AssignedByUserID)
	var i StreetLeaderAssignment
	err := row.Scan(
		&i.ID,
		&i.StreetID,
		&i.UserID,
		&i.AssignedByUserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateActiveStreetLeaderAssignmentForStreet = `-- name: DeactivateActiveStreetLeaderAssignmentForStreet :exec
UPDATE street_leader_assignments
SET is_active = false, updated_at = now()
WHERE street_id = $1 AND is_active = true
`

func (q *Queries) DeactivateActiveStreetLeaderAssignmentForStreet(ctx context.Context, streetID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateActiveStreetLeaderAssignmentForStreet, streetID)
	return err
}

const getActiveStreetLeaderAssignmentByStreetID = `-- name: GetActiveStreetLeaderAssignmentByStreetID :one
SELECT id, street_id, user_id, assigned_by_user_id, is_active, created_at, updated_at FROM street_leader_assignments
WHERE street_id = $1 AND is_active = true
`

func (q *Queries) GetActiveStreetLeaderAssignmentByStreetID(ctx context.Context, streetID pgtype.UUID) (StreetLeaderAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveStreetLeaderAssignmentByStreetID, streetID)
	var i StreetLeaderAssignment
	err := row.Scan(
		&i.ID,
		&i.StreetID,
		&i.UserID,
		&i.AssignedByUserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isUserAssignedToStreet = `-- name: IsUserAssignedToStreet :one
SELECT EXISTS (
    SELECT 1
    FROM street_leader_assignments
    WHERE street_id = $1 AND user_id = $2 AND is_active = true
) AS is_assigned
`

type IsUserAssignedToStreetParams struct {
	StreetID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) IsUserAssignedToStreet(ctx context.Context, arg IsUserAssignedToStreetParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAssignedToStreet, arg.StreetID, arg.UserID)
	var is_assigned bool
	err := row.Scan(&is_assigned)
	return is_assigned, err
}

const listStreetLeaderAssignmentsByStreetID = `-- name: ListStreetLeaderAssignmentsByStreetID :many
SELECT id, street_id, user_id, assigned_by_user_id, is_active, created_at, updated_at FROM street_leader_assignments
WHERE street_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStreetLeaderAssignmentsByStreetID(ctx context.Context, streetID pgtype.UUID) ([]StreetLeaderAssignment, error) {
	rows, err := q.db.Query(ctx, listStreetLeaderAssignmentsByStreetID, streetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreetLeaderAssignment
	for rows.Next() {
		var i StreetLeaderAssignment
		if err := rows.Scan(
			&i.ID,
			&i.StreetID,
			&i.UserID,
			&i.AssignedByUserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreetLeaderAssignmentsByUserID = `-- name: ListStreetLeaderAssignmentsByUserID :many
SELECT id, street_id, user_id, assigned_by_user_id, is_active, created_at, updated_at FROM street_leader_assignments
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStreetLeaderAssignmentsByUserID(ctx context.Context, userID pgtype.UUID) ([]StreetLeaderAssignment, error) {
	rows, err := q.db.Query(ctx, listStreetLeaderAssignmentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreetLeaderAssignment
	for rows.Next() {
		var i StreetLeaderAssignment
		if err := rows.Scan(
			&i.ID,
			&i.StreetID,
			&i.UserID,
			&i.AssignedByUserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
