// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStreet = `-- name: CreateStreet :one
INSERT INTO streets (
    mfy_id,
    name,
    planned_households_count,
    notes,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, mfy_id, name, planned_households_count, notes, is_active, created_by_user_id, created_at, updated_at
`

type CreateStreetParams struct {
	MfyID                  pgtype.UUID
	Name                   string
	PlannedHouseholdsCount int32
	Notes                  pgtype.Text
	CreatedByUserID        pgtype.UUID
}

func (q *Queries) CreateStreet(ctx context.Context, arg CreateStreetParams) (Street, error) {
	row := q.db.QueryRow(ctx, createStreet,
		arg.MfyID,
		arg.Name,
		arg.PlannedHouseholdsCount,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i Street
	err := row.Scan(
		&i.ID,
		&i.MfyID,
		&i.Name,
		&i.PlannedHouseholdsCount,
		&i.Notes,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStreetByID = `-- name: GetStreetByID :one
SELECT id, mfy_id, name, planned_households_count, notes, is_active, created_by_user_id, created_at, updated_at FROM streets
WHERE id = $1
`

func (q *Queries) GetStreetByID(ctx context.Context, id pgtype.UUID) (Street, error) {
	row := q.db.QueryRow(ctx, getStreetByID, id)
	var i Street
	err := row.Scan(
		&i.ID,
		&i.MfyID,
		&i.Name,
		&i.PlannedHouseholdsCount,
		&i.Notes,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStreetsByMFYID = `-- name: ListStreetsByMFYID :many
SELECT id, mfy_id, name, planned_households_count, notes, is_active, created_by_user_id, created_at, updated_at FROM streets
WHERE mfy_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListStreetsByMFYIDParams struct {
	MfyID  pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListStreetsByMFYID(ctx context.Context, arg ListStreetsByMFYIDParams) ([]Street, error) {
	rows, err := q.db.Query(ctx, listStreetsByMFYID, arg.MfyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Street
	for rows.Next() {
		var i Street
		if err := rows.Scan(
			&i.ID,
			&i.MfyID,
			&i.Name,
			&i.PlannedHouseholdsCount,
			&i.Notes,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreetsForStreetLeader = `-- name: ListStreetsForStreetLeader :many
SELECT s.id, s.mfy_id, s.name, s.planned_households_count, s.notes, s.is_active, s.created_by_user_id, s.created_at, s.updated_at
FROM streets s
JOIN street_leader_assignments sla ON sla.street_id = s.id
WHERE sla.user_id = $1 AND sla.is_active = true AND s.is_active = true
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListStreetsForStreetLeaderParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListStreetsForStreetLeader(ctx context.Context, arg ListStreetsForStreetLeaderParams) ([]Street, error) {
	rows, err := q.db.Query(ctx, listStreetsForStreetLeader, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Street
	for rows.Next() {
		var i Street
		if err := rows.Scan(
			&i.ID,
			&i.MfyID,
			&i.Name,
			&i.PlannedHouseholdsCount,
			&i.Notes,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStreetActive = `-- name: SetStreetActive :one
UPDATE streets
SET is_active = $2, updated_at = now()
WHERE id = $1
RETURNING id, mfy_id, name, planned_households_count, notes, is_active, created_by_user_id, created_at, updated_at
`

type SetStreetActiveParams struct {
	ID       pgtype.UUID
	IsActive bool
}

func (q *Queries) SetStreetActive(ctx context.Context, arg SetStreetActiveParams) (Street, error) {
	row := q.db.QueryRow(ctx, setStreetActive, arg.ID, arg.IsActive)
	var i Street
	err := row.Scan(
		&i.ID,
		&i.MfyID,
		&i.Name,
		&i.PlannedHouseholdsCount,
		&i.Notes,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStreet = `-- name: UpdateStreet :one
UPDATE streets
SET
    name = $2,
    planned_households_count = $3,
    notes = $4,
    is_active = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, mfy_id, name, planned_households_count, notes, is_active, created_by_user_id, created_at, updated_at
`

type UpdateStreetParams struct {
	ID                     pgtype.UUID
	Name                   string
	PlannedHouseholdsCount int32
	Notes                  pgtype.Text
	IsActive               bool
}

func (q *Queries) UpdateStreet(ctx context.Context, arg UpdateStreetParams) (Street, error) {
	row := q.db.QueryRow(ctx, updateStreet,
		arg.ID,
		arg.Name,
		arg.PlannedHouseholdsCount,
		arg.Notes,
		arg.IsActive,
	)
	var i Street
	err := row.Scan(
		&i.ID,
		&i.MfyID,
		&i.Name,
		&i.PlannedHouseholdsCount,
		&i.Notes,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
