// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users
SET is_active = true, updated_at = now()
WHERE id = $1
RETURNING id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at
`

func (q *Queries) ActivateUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, activateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.Role,
		&i.MfyID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name,
    phone,
    telegram_id,
    telegram_username,
    role,
    mfy_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at
`

type CreateUserParams struct {
	FullName         string
	Phone            pgtype.Text
	TelegramID       pgtype.Int8
	TelegramUsername pgtype.Text
	Role             string
	MfyID            pgtype.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Phone,
		arg.TelegramID,
		arg.TelegramUsername,
		arg.Role,
		arg.MfyID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.Role,
		&i.MfyID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active = false, updated_at = now()
WHERE id = $1
RETURNING id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.Role,
		&i.MfyID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.Role,
		&i.MfyID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at FROM users
WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID pgtype.Int8) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.Role,
		&i.MfyID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.TelegramID,
			&i.TelegramUsername,
			&i.Role,
			&i.MfyID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserTelegramIdentity = `-- name: SetUserTelegramIdentity :one
UPDATE users
SET
    telegram_id = $2,
    telegram_username = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at
`

type SetUserTelegramIdentityParams struct {
	ID               pgtype.UUID
	TelegramID       pgtype.Int8
	TelegramUsername pgtype.Text
}

func (q *Queries) SetUserTelegramIdentity(ctx context.Context, arg SetUserTelegramIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserTelegramIdentity, arg.ID, arg.TelegramID, arg.TelegramUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.Role,
		&i.MfyID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name = $2,
    phone = $3,
    role = $4,
    mfy_id = $5,
    is_active = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, full_name, phone, telegram_id, telegram_username, role, mfy_id, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID       pgtype.UUID
	FullName string
	Phone    pgtype.Text
	Role     string
	MfyID    pgtype.UUID
	IsActive bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.Role,
		arg.MfyID,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.Role,
		&i.MfyID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
